org: carlosrenatohr
app: chat-b2c-lambda
service: chat-b2c-lambda

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

custom:
 wsgi:
   app: app.app
   packRequirements: false

functions:
 api:
   handler: wsgi_handler.handler
   events:
     - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements